language: node_js
node_js:
  - "6.1"
cache:
  directories:
    - node_modules

branches:
  only:
  - react

install:
  - npm install

script:
- CI=true npm test

after_success:
- CI=true npm test -- --coverage | coveralls